/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caixeiroviajante;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author ramir
 */
public class Inicializador {
    
    public static List getCidades () {
        List cidades = new ArrayList<Cidade>();
        cidades.add(Inicializador.setCidade(1, "Aracajú"));
        cidades.add(Inicializador.setCidade(2, "Belém"));
        cidades.add(Inicializador.setCidade(3, "Belo Horizonte"));
        cidades.add(Inicializador.setCidade(4, "Boa Vista"));
        cidades.add(Inicializador.setCidade(5, "Brasília"));
        cidades.add(Inicializador.setCidade(6, "Campo Grande"));
        cidades.add(Inicializador.setCidade(7, "Cuiabá"));
        cidades.add(Inicializador.setCidade(8, "Curitiba"));
        cidades.add(Inicializador.setCidade(9, "Florianópolis"));
        cidades.add(Inicializador.setCidade(10, "Fortaleza"));
        cidades.add(Inicializador.setCidade(11, "Goiânia"));
        cidades.add(Inicializador.setCidade(12, "João Pessoa"));
        cidades.add(Inicializador.setCidade(13, "Maceió"));
        cidades.add(Inicializador.setCidade(14, "Manaus"));
        cidades.add(Inicializador.setCidade(15, "Natal"));
        cidades.add(Inicializador.setCidade(16, "Palmas"));
        cidades.add(Inicializador.setCidade(17, "Porto Alegre"));
        cidades.add(Inicializador.setCidade(18, "Porto Velho"));
        cidades.add(Inicializador.setCidade(19, "Recife"));
        cidades.add(Inicializador.setCidade(20, "Rio Branco"));
        cidades.add(Inicializador.setCidade(21, "Rio de Janeiro"));
        cidades.add(Inicializador.setCidade(22, "Salvador"));
        cidades.add(Inicializador.setCidade(23, "São Luis"));
        cidades.add(Inicializador.setCidade(24, "São Paulo"));
        cidades.add(Inicializador.setCidade(25, "Teresina"));
        cidades.add(Inicializador.setCidade(26, "Vitória"));
        
        for (int i = 0; i < cidades.size(); i++) {
            
        }
        
        return cidades;
    }
    
    public static Cidade setCidade(int id, String nome) {
        Cidade cidade = new Cidade();
        cidade.idCidade = id;
        cidade.nomeCidade = nome;
        
        List distancias = new ArrayList<DistanciaCidades>();
        distancias = getDistancias(id);
        cidade.distancias = distancias;
                
        return cidade;
    }
    
    public static List getDistancias(int idCidade) {
        List distancias = new ArrayList<DistanciaCidades>();
        
        switch(idCidade)
        {
            //distancias.add(setDistanciaCidade(idCidade, , ));
            case 1:
                distancias.add(setDistanciaCidade(idCidade, 2, 2079));
                distancias.add(setDistanciaCidade(idCidade, 3, 1578));
                distancias.add(setDistanciaCidade(idCidade, 4, 6000));
                distancias.add(setDistanciaCidade(idCidade, 5, 1652));
                distancias.add(setDistanciaCidade(idCidade, 6, 2765));
                distancias.add(setDistanciaCidade(idCidade, 7, 2775));
                distancias.add(setDistanciaCidade(idCidade, 8, 2595));
                distancias.add(setDistanciaCidade(idCidade, 9, 2892));
                distancias.add(setDistanciaCidade(idCidade, 10, 1183));
                distancias.add(setDistanciaCidade(idCidade, 11, 1848));
                distancias.add(setDistanciaCidade(idCidade, 12, 611));
                distancias.add(setDistanciaCidade(idCidade, 13, 294));
                distancias.add(setDistanciaCidade(idCidade, 14, 5215));
                distancias.add(setDistanciaCidade(idCidade, 15, 788));
                distancias.add(setDistanciaCidade(idCidade, 16, 1662));
                distancias.add(setDistanciaCidade(idCidade, 17, 3296));
                distancias.add(setDistanciaCidade(idCidade, 18, 4230));
                distancias.add(setDistanciaCidade(idCidade, 19, 501));
                distancias.add(setDistanciaCidade(idCidade, 20, 4763));
                distancias.add(setDistanciaCidade(idCidade, 21, 1855));
                distancias.add(setDistanciaCidade(idCidade, 22, 356));
                distancias.add(setDistanciaCidade(idCidade, 23, 1578));
                distancias.add(setDistanciaCidade(idCidade, 24, 2187));
                distancias.add(setDistanciaCidade(idCidade, 25, 1142));
                distancias.add(setDistanciaCidade(idCidade, 26, 1408));
                break;
            case 2:
                distancias.add(setDistanciaCidade(idCidade, 1, 2079));
                distancias.add(setDistanciaCidade(idCidade, 3, 2824));
                distancias.add(setDistanciaCidade(idCidade, 4, 6083));
                distancias.add(setDistanciaCidade(idCidade, 5, 2120));
                distancias.add(setDistanciaCidade(idCidade, 6, 2942));
                distancias.add(setDistanciaCidade(idCidade, 7, 2941));
                distancias.add(setDistanciaCidade(idCidade, 8, 3193));
                distancias.add(setDistanciaCidade(idCidade, 9, 3500));
                distancias.add(setDistanciaCidade(idCidade, 10, 1610));
                distancias.add(setDistanciaCidade(idCidade, 11, 2017));
                distancias.add(setDistanciaCidade(idCidade, 12, 2161));
                distancias.add(setDistanciaCidade(idCidade, 13, 2173));
                distancias.add(setDistanciaCidade(idCidade, 14, 5298));
                distancias.add(setDistanciaCidade(idCidade, 15, 2108));
                distancias.add(setDistanciaCidade(idCidade, 16, 1283));
                distancias.add(setDistanciaCidade(idCidade, 17, 3852));
                distancias.add(setDistanciaCidade(idCidade, 18, 4397));
                distancias.add(setDistanciaCidade(idCidade, 19, 2074));
                distancias.add(setDistanciaCidade(idCidade, 20, 4931));
                distancias.add(setDistanciaCidade(idCidade, 21, 3250));
                distancias.add(setDistanciaCidade(idCidade, 22, 2100));
                distancias.add(setDistanciaCidade(idCidade, 23, 806));
                distancias.add(setDistanciaCidade(idCidade, 24, 2933));
                distancias.add(setDistanciaCidade(idCidade, 25, 947));
                distancias.add(setDistanciaCidade(idCidade, 26, 3108));
                break;
            case 4:
                distancias.add(setDistanciaCidade(idCidade, 1, 6000));
                distancias.add(setDistanciaCidade(idCidade, 2, 6083));
                distancias.add(setDistanciaCidade(idCidade, 3, 4736));
                distancias.add(setDistanciaCidade(idCidade, 5, 4275));
                distancias.add(setDistanciaCidade(idCidade, 6, 3836));
                distancias.add(setDistanciaCidade(idCidade, 7, 3142));
                distancias.add(setDistanciaCidade(idCidade, 8, 4821));
                distancias.add(setDistanciaCidade(idCidade, 9, 5128));
                distancias.add(setDistanciaCidade(idCidade, 10, 6548));
                distancias.add(setDistanciaCidade(idCidade, 11, 4076));
                distancias.add(setDistanciaCidade(idCidade, 12, 6593));
                distancias.add(setDistanciaCidade(idCidade, 13, 6279));
                distancias.add(setDistanciaCidade(idCidade, 14, 785));
                distancias.add(setDistanciaCidade(idCidade, 15, 6770));
                distancias.add(setDistanciaCidade(idCidade, 16, 4926));
                distancias.add(setDistanciaCidade(idCidade, 17, 5348));
                distancias.add(setDistanciaCidade(idCidade, 18, 1686));
                distancias.add(setDistanciaCidade(idCidade, 19, 6483));
                distancias.add(setDistanciaCidade(idCidade, 20, 2230));
                distancias.add(setDistanciaCidade(idCidade, 21, 5159));
                distancias.add(setDistanciaCidade(idCidade, 22, 5794));
                distancias.add(setDistanciaCidade(idCidade, 23, 6120));
                distancias.add(setDistanciaCidade(idCidade, 24, 4756));
                distancias.add(setDistanciaCidade(idCidade, 25, 6052));
                distancias.add(setDistanciaCidade(idCidade, 26, 5261));
                break;
            case 5:
                distancias.add(setDistanciaCidade(idCidade, 1, 1652));
                distancias.add(setDistanciaCidade(idCidade, 2, 2120));
                distancias.add(setDistanciaCidade(idCidade, 3, 716));
                distancias.add(setDistanciaCidade(idCidade, 4, 4275));
                distancias.add(setDistanciaCidade(idCidade, 6, 1134));
                distancias.add(setDistanciaCidade(idCidade, 7, 1133));
                distancias.add(setDistanciaCidade(idCidade, 8, 1366));
                distancias.add(setDistanciaCidade(idCidade, 9, 1673));
                distancias.add(setDistanciaCidade(idCidade, 10, 2200));
                distancias.add(setDistanciaCidade(idCidade, 11, 209));
                distancias.add(setDistanciaCidade(idCidade, 12, 2245));
                distancias.add(setDistanciaCidade(idCidade, 13, 1930));
                distancias.add(setDistanciaCidade(idCidade, 14, 3490));
                distancias.add(setDistanciaCidade(idCidade, 15, 2422));
                distancias.add(setDistanciaCidade(idCidade, 16, 973));
                distancias.add(setDistanciaCidade(idCidade, 17, 2027));
                distancias.add(setDistanciaCidade(idCidade, 18, 2589));
                distancias.add(setDistanciaCidade(idCidade, 19, 2135));
                distancias.add(setDistanciaCidade(idCidade, 20, 3123));
                distancias.add(setDistanciaCidade(idCidade, 21, 1148));
                distancias.add(setDistanciaCidade(idCidade, 22, 1446));
                distancias.add(setDistanciaCidade(idCidade, 23, 2157));
                distancias.add(setDistanciaCidade(idCidade, 24, 1015));
                distancias.add(setDistanciaCidade(idCidade, 25, 1789));
                distancias.add(setDistanciaCidade(idCidade, 26, 1239));
                break;
            case 6:
                distancias.add(setDistanciaCidade(idCidade, 1, 2765));
                distancias.add(setDistanciaCidade(idCidade, 2, 2942));
                distancias.add(setDistanciaCidade(idCidade, 3, 1453));
                distancias.add(setDistanciaCidade(idCidade, 4, 3836));
                distancias.add(setDistanciaCidade(idCidade, 5, 1134));
                distancias.add(setDistanciaCidade(idCidade, 7, 694));
                distancias.add(setDistanciaCidade(idCidade, 8, 991));
                distancias.add(setDistanciaCidade(idCidade, 9, 1298));
                distancias.add(setDistanciaCidade(idCidade, 10, 3407));
                distancias.add(setDistanciaCidade(idCidade, 11, 935));
                distancias.add(setDistanciaCidade(idCidade, 12, 3357));
                distancias.add(setDistanciaCidade(idCidade, 13, 3040));
                distancias.add(setDistanciaCidade(idCidade, 14, 3051));
                distancias.add(setDistanciaCidade(idCidade, 15, 3534));
                distancias.add(setDistanciaCidade(idCidade, 16, 1785));
                distancias.add(setDistanciaCidade(idCidade, 17, 1518));
                distancias.add(setDistanciaCidade(idCidade, 18, 2150));
                distancias.add(setDistanciaCidade(idCidade, 19, 3247));
                distancias.add(setDistanciaCidade(idCidade, 20, 2684));
                distancias.add(setDistanciaCidade(idCidade, 21, 1444));
                distancias.add(setDistanciaCidade(idCidade, 22, 2568));
                distancias.add(setDistanciaCidade(idCidade, 23, 2979));
                distancias.add(setDistanciaCidade(idCidade, 24, 1014));
                distancias.add(setDistanciaCidade(idCidade, 25, 2911));
                distancias.add(setDistanciaCidade(idCidade, 26, 1892));
                break;
            case 7:
                distancias.add(setDistanciaCidade(idCidade, 1, 2775));
                distancias.add(setDistanciaCidade(idCidade, 2, 2941));
                distancias.add(setDistanciaCidade(idCidade, 3, 1594));
                distancias.add(setDistanciaCidade(idCidade, 4, 3142));
                distancias.add(setDistanciaCidade(idCidade, 5, 1133));
                distancias.add(setDistanciaCidade(idCidade, 6, 694));
                distancias.add(setDistanciaCidade(idCidade, 8, 1679));
                distancias.add(setDistanciaCidade(idCidade, 9, 1986));
                distancias.add(setDistanciaCidade(idCidade, 10, 3406));
                distancias.add(setDistanciaCidade(idCidade, 11, 934));
                distancias.add(setDistanciaCidade(idCidade, 12, 3366));
                distancias.add(setDistanciaCidade(idCidade, 13, 3049));
                distancias.add(setDistanciaCidade(idCidade, 14, 2357));
                distancias.add(setDistanciaCidade(idCidade, 15, 3543));
                distancias.add(setDistanciaCidade(idCidade, 16, 1784));
                distancias.add(setDistanciaCidade(idCidade, 17, 2206));
                distancias.add(setDistanciaCidade(idCidade, 18, 1456));
                distancias.add(setDistanciaCidade(idCidade, 19, 3255));
                distancias.add(setDistanciaCidade(idCidade, 20, 1990));
                distancias.add(setDistanciaCidade(idCidade, 21, 2017));
                distancias.add(setDistanciaCidade(idCidade, 22, 2566));
                distancias.add(setDistanciaCidade(idCidade, 23, 2978));
                distancias.add(setDistanciaCidade(idCidade, 24, 1614));
                distancias.add(setDistanciaCidade(idCidade, 25, 2910));
                distancias.add(setDistanciaCidade(idCidade, 26, 2119));
                break;
            case 8:
                distancias.add(setDistanciaCidade(idCidade, 1, 2595));
                distancias.add(setDistanciaCidade(idCidade, 2, 3193));
                distancias.add(setDistanciaCidade(idCidade, 3, 1004));
                distancias.add(setDistanciaCidade(idCidade, 4, 4821));
                distancias.add(setDistanciaCidade(idCidade, 5, 1366));
                distancias.add(setDistanciaCidade(idCidade, 6, 991));
                distancias.add(setDistanciaCidade(idCidade, 7, 1679));
                distancias.add(setDistanciaCidade(idCidade, 9, 300));
                distancias.add(setDistanciaCidade(idCidade, 10, 3541));
                distancias.add(setDistanciaCidade(idCidade, 11, 1186));
                distancias.add(setDistanciaCidade(idCidade, 12, 3188));
                distancias.add(setDistanciaCidade(idCidade, 13, 2871));
                distancias.add(setDistanciaCidade(idCidade, 14, 4036));
                distancias.add(setDistanciaCidade(idCidade, 15, 3365));
                distancias.add(setDistanciaCidade(idCidade, 16, 2036));
                distancias.add(setDistanciaCidade(idCidade, 17, 711));
                distancias.add(setDistanciaCidade(idCidade, 18, 3135));
                distancias.add(setDistanciaCidade(idCidade, 19, 3078));
                distancias.add(setDistanciaCidade(idCidade, 20, 3669));
                distancias.add(setDistanciaCidade(idCidade, 21, 852));
                distancias.add(setDistanciaCidade(idCidade, 22, 2385));
                distancias.add(setDistanciaCidade(idCidade, 23, 3230));
                distancias.add(setDistanciaCidade(idCidade, 24, 408));
                distancias.add(setDistanciaCidade(idCidade, 25, 3143));
                distancias.add(setDistanciaCidade(idCidade, 26, 1300));
                break;
            case 9:
                distancias.add(setDistanciaCidade(idCidade, 1, 2892));
                distancias.add(setDistanciaCidade(idCidade, 2, 3500));
                distancias.add(setDistanciaCidade(idCidade, 3, 1301));
                distancias.add(setDistanciaCidade(idCidade, 4, 5128));
                distancias.add(setDistanciaCidade(idCidade, 5, 1673));
                distancias.add(setDistanciaCidade(idCidade, 6, 1298));
                distancias.add(setDistanciaCidade(idCidade, 7, 1986));
                distancias.add(setDistanciaCidade(idCidade, 8, 300));
                distancias.add(setDistanciaCidade(idCidade, 10, 3838));
                distancias.add(setDistanciaCidade(idCidade, 11, 1493));
                distancias.add(setDistanciaCidade(idCidade, 12, 3485));
                distancias.add(setDistanciaCidade(idCidade, 13, 3168));
                distancias.add(setDistanciaCidade(idCidade, 14, 4443));
                distancias.add(setDistanciaCidade(idCidade, 15, 3662));
                distancias.add(setDistanciaCidade(idCidade, 16, 2336));
                distancias.add(setDistanciaCidade(idCidade, 17, 476));
                distancias.add(setDistanciaCidade(idCidade, 18, 3442));
                distancias.add(setDistanciaCidade(idCidade, 19, 3375));
                distancias.add(setDistanciaCidade(idCidade, 20, 3976));
                distancias.add(setDistanciaCidade(idCidade, 21, 1144));
                distancias.add(setDistanciaCidade(idCidade, 22, 2682));
                distancias.add(setDistanciaCidade(idCidade, 23, 3537));
                distancias.add(setDistanciaCidade(idCidade, 24, 705));
                distancias.add(setDistanciaCidade(idCidade, 25, 3450));
                distancias.add(setDistanciaCidade(idCidade, 26, 1597));
                break;
            case 10:
                distancias.add(setDistanciaCidade(idCidade, 1, 1183));
                distancias.add(setDistanciaCidade(idCidade, 2, 1610));
                distancias.add(setDistanciaCidade(idCidade, 3, 2528));
                distancias.add(setDistanciaCidade(idCidade, 4, 6548));
                distancias.add(setDistanciaCidade(idCidade, 5, 2200));
                distancias.add(setDistanciaCidade(idCidade, 6, 3407));
                distancias.add(setDistanciaCidade(idCidade, 7, 3406));
                distancias.add(setDistanciaCidade(idCidade, 8, 3541));
                distancias.add(setDistanciaCidade(idCidade, 9, 3838));
                distancias.add(setDistanciaCidade(idCidade, 11, 2482));
                distancias.add(setDistanciaCidade(idCidade, 12, 688));
                distancias.add(setDistanciaCidade(idCidade, 13, 1075));
                distancias.add(setDistanciaCidade(idCidade, 14, 5763));
                distancias.add(setDistanciaCidade(idCidade, 15, 537));
                distancias.add(setDistanciaCidade(idCidade, 16, 2035));
                distancias.add(setDistanciaCidade(idCidade, 17, 4242));
                distancias.add(setDistanciaCidade(idCidade, 18, 4862));
                distancias.add(setDistanciaCidade(idCidade, 19, 800));
                distancias.add(setDistanciaCidade(idCidade, 20, 5396));
                distancias.add(setDistanciaCidade(idCidade, 21, 2805));
                distancias.add(setDistanciaCidade(idCidade, 22, 1389));
                distancias.add(setDistanciaCidade(idCidade, 23, 1070));
                distancias.add(setDistanciaCidade(idCidade, 24, 3127));
                distancias.add(setDistanciaCidade(idCidade, 25, 634));
                distancias.add(setDistanciaCidade(idCidade, 26, 2397));
                break;
            case 11:
                distancias.add(setDistanciaCidade(idCidade, 1, 1848));
                distancias.add(setDistanciaCidade(idCidade, 2, 2017));
                distancias.add(setDistanciaCidade(idCidade, 3, 906));
                distancias.add(setDistanciaCidade(idCidade, 4, 4076));
                distancias.add(setDistanciaCidade(idCidade, 5, 209));
                distancias.add(setDistanciaCidade(idCidade, 6, 935));
                distancias.add(setDistanciaCidade(idCidade, 7, 934));
                distancias.add(setDistanciaCidade(idCidade, 8, 1186));
                distancias.add(setDistanciaCidade(idCidade, 9, 1493));
                distancias.add(setDistanciaCidade(idCidade, 10, 2482));
                distancias.add(setDistanciaCidade(idCidade, 12, 2442));
                distancias.add(setDistanciaCidade(idCidade, 13, 2125));
                distancias.add(setDistanciaCidade(idCidade, 14, 3291));
                distancias.add(setDistanciaCidade(idCidade, 15, 2618));
                distancias.add(setDistanciaCidade(idCidade, 16, 874));
                distancias.add(setDistanciaCidade(idCidade, 17, 1847));
                distancias.add(setDistanciaCidade(idCidade, 18, 2390));
                distancias.add(setDistanciaCidade(idCidade, 19, 2332));
                distancias.add(setDistanciaCidade(idCidade, 20, 2924));
                distancias.add(setDistanciaCidade(idCidade, 21, 1338));
                distancias.add(setDistanciaCidade(idCidade, 22, 1643));
                distancias.add(setDistanciaCidade(idCidade, 23, 2054));
                distancias.add(setDistanciaCidade(idCidade, 24, 926));
                distancias.add(setDistanciaCidade(idCidade, 25, 1986));
                distancias.add(setDistanciaCidade(idCidade, 26, 1428));
                break;
            case 12:
                distancias.add(setDistanciaCidade(idCidade, 1, 611));
                distancias.add(setDistanciaCidade(idCidade, 2, 2161));
                distancias.add(setDistanciaCidade(idCidade, 3, 2171));
                distancias.add(setDistanciaCidade(idCidade, 4, 6593));
                distancias.add(setDistanciaCidade(idCidade, 5, 2245));
                distancias.add(setDistanciaCidade(idCidade, 6, 3357));
                distancias.add(setDistanciaCidade(idCidade, 7, 3366));
                distancias.add(setDistanciaCidade(idCidade, 8, 3188));
                distancias.add(setDistanciaCidade(idCidade, 9, 3485));
                distancias.add(setDistanciaCidade(idCidade, 10, 688));
                distancias.add(setDistanciaCidade(idCidade, 11, 2442));
                distancias.add(setDistanciaCidade(idCidade, 13, 395));
                distancias.add(setDistanciaCidade(idCidade, 14, 5808));
                distancias.add(setDistanciaCidade(idCidade, 15, 185));
                distancias.add(setDistanciaCidade(idCidade, 16, 2253));
                distancias.add(setDistanciaCidade(idCidade, 17, 3889));
                distancias.add(setDistanciaCidade(idCidade, 18, 4822));
                distancias.add(setDistanciaCidade(idCidade, 19, 120));
                distancias.add(setDistanciaCidade(idCidade, 20, 5356));
                distancias.add(setDistanciaCidade(idCidade, 21, 2448));
                distancias.add(setDistanciaCidade(idCidade, 22, 949));
                distancias.add(setDistanciaCidade(idCidade, 23, 1660));
                distancias.add(setDistanciaCidade(idCidade, 24, 2770));
                distancias.add(setDistanciaCidade(idCidade, 25, 1224));
                distancias.add(setDistanciaCidade(idCidade, 26, 2001));
                break;
            case 13:
                distancias.add(setDistanciaCidade(idCidade, 1, 294));
                distancias.add(setDistanciaCidade(idCidade, 2, 2173));
                distancias.add(setDistanciaCidade(idCidade, 3, 1854));
                distancias.add(setDistanciaCidade(idCidade, 4, 6279));
                distancias.add(setDistanciaCidade(idCidade, 5, 1930));
                distancias.add(setDistanciaCidade(idCidade, 6, 3040));
                distancias.add(setDistanciaCidade(idCidade, 7, 3049));
                distancias.add(setDistanciaCidade(idCidade, 8, 2871));
                distancias.add(setDistanciaCidade(idCidade, 9, 3168));
                distancias.add(setDistanciaCidade(idCidade, 10, 1075));
                distancias.add(setDistanciaCidade(idCidade, 11, 2125));
                distancias.add(setDistanciaCidade(idCidade, 12, 395));
                distancias.add(setDistanciaCidade(idCidade, 14, 5491));
                distancias.add(setDistanciaCidade(idCidade, 15, 572));
                distancias.add(setDistanciaCidade(idCidade, 16, 1851));
                distancias.add(setDistanciaCidade(idCidade, 17, 3572));
                distancias.add(setDistanciaCidade(idCidade, 18, 4505));
                distancias.add(setDistanciaCidade(idCidade, 19, 285));
                distancias.add(setDistanciaCidade(idCidade, 20, 5039));
                distancias.add(setDistanciaCidade(idCidade, 21, 2131));
                distancias.add(setDistanciaCidade(idCidade, 22, 632));
                distancias.add(setDistanciaCidade(idCidade, 23, 1672));
                distancias.add(setDistanciaCidade(idCidade, 24, 2453));
                distancias.add(setDistanciaCidade(idCidade, 25, 1236));
                distancias.add(setDistanciaCidade(idCidade, 26, 1684));
                break;
            case 14:
                distancias.add(setDistanciaCidade(idCidade, 1, 5215));
                distancias.add(setDistanciaCidade(idCidade, 2, 5298));
                distancias.add(setDistanciaCidade(idCidade, 3, 3951));
                distancias.add(setDistanciaCidade(idCidade, 4, 785));
                distancias.add(setDistanciaCidade(idCidade, 5, 3490));
                distancias.add(setDistanciaCidade(idCidade, 6, 3051));
                distancias.add(setDistanciaCidade(idCidade, 7, 2357));
                distancias.add(setDistanciaCidade(idCidade, 8, 4036));
                distancias.add(setDistanciaCidade(idCidade, 9, 4443));
                distancias.add(setDistanciaCidade(idCidade, 10, 5763));
                distancias.add(setDistanciaCidade(idCidade, 11, 3291));
                distancias.add(setDistanciaCidade(idCidade, 12, 5808));
                distancias.add(setDistanciaCidade(idCidade, 13, 5491));
                distancias.add(setDistanciaCidade(idCidade, 15, 5985));
                distancias.add(setDistanciaCidade(idCidade, 16, 4141));
                distancias.add(setDistanciaCidade(idCidade, 17, 4563));
                distancias.add(setDistanciaCidade(idCidade, 18, 901));
                distancias.add(setDistanciaCidade(idCidade, 19, 5698));
                distancias.add(setDistanciaCidade(idCidade, 20, 1445));
                distancias.add(setDistanciaCidade(idCidade, 21, 4374));
                distancias.add(setDistanciaCidade(idCidade, 22, 5009));
                distancias.add(setDistanciaCidade(idCidade, 23, 5335));
                distancias.add(setDistanciaCidade(idCidade, 24, 3971));
                distancias.add(setDistanciaCidade(idCidade, 25, 5267));
                distancias.add(setDistanciaCidade(idCidade, 26, 4476));
                break;
            case 15:
                distancias.add(setDistanciaCidade(idCidade, 1, 788));
                distancias.add(setDistanciaCidade(idCidade, 2, 2108));
                distancias.add(setDistanciaCidade(idCidade, 3, 2348));
                distancias.add(setDistanciaCidade(idCidade, 4, 6770));
                distancias.add(setDistanciaCidade(idCidade, 5, 2422));
                distancias.add(setDistanciaCidade(idCidade, 6, 3534));
                distancias.add(setDistanciaCidade(idCidade, 7, 3543));
                distancias.add(setDistanciaCidade(idCidade, 8, 3365));
                distancias.add(setDistanciaCidade(idCidade, 9, 3662));
                distancias.add(setDistanciaCidade(idCidade, 10, 537));
                distancias.add(setDistanciaCidade(idCidade, 11, 2618));
                distancias.add(setDistanciaCidade(idCidade, 12, 185));
                distancias.add(setDistanciaCidade(idCidade, 13, 572));
                distancias.add(setDistanciaCidade(idCidade, 14, 5985));
                distancias.add(setDistanciaCidade(idCidade, 16, 2345));
                distancias.add(setDistanciaCidade(idCidade, 17, 4066));
                distancias.add(setDistanciaCidade(idCidade, 18, 4998));
                distancias.add(setDistanciaCidade(idCidade, 19, 297));
                distancias.add(setDistanciaCidade(idCidade, 20, 5533));
                distancias.add(setDistanciaCidade(idCidade, 21, 2625));
                distancias.add(setDistanciaCidade(idCidade, 22, 1126));
                distancias.add(setDistanciaCidade(idCidade, 23, 1607));
                distancias.add(setDistanciaCidade(idCidade, 24, 2947));
                distancias.add(setDistanciaCidade(idCidade, 25, 1171));
                distancias.add(setDistanciaCidade(idCidade, 26, 2178));
                break;
            case 16:
                distancias.add(setDistanciaCidade(idCidade, 1, 1662));
                distancias.add(setDistanciaCidade(idCidade, 2, 1283));
                distancias.add(setDistanciaCidade(idCidade, 3, 1690));
                distancias.add(setDistanciaCidade(idCidade, 4, 4926));
                distancias.add(setDistanciaCidade(idCidade, 5, 973));
                distancias.add(setDistanciaCidade(idCidade, 6, 1785));
                distancias.add(setDistanciaCidade(idCidade, 7, 1784));
                distancias.add(setDistanciaCidade(idCidade, 8, 2036));
                distancias.add(setDistanciaCidade(idCidade, 9, 2336));
                distancias.add(setDistanciaCidade(idCidade, 10, 2035));
                distancias.add(setDistanciaCidade(idCidade, 11, 874));
                distancias.add(setDistanciaCidade(idCidade, 12, 2253));
                distancias.add(setDistanciaCidade(idCidade, 13, 1851));
                distancias.add(setDistanciaCidade(idCidade, 14, 4141));
                distancias.add(setDistanciaCidade(idCidade, 15, 2345));
                distancias.add(setDistanciaCidade(idCidade, 17, 2747));
                distancias.add(setDistanciaCidade(idCidade, 18, 2970));
                distancias.add(setDistanciaCidade(idCidade, 19, 2058));
                distancias.add(setDistanciaCidade(idCidade, 20, 3764));
                distancias.add(setDistanciaCidade(idCidade, 21, 2124));
                distancias.add(setDistanciaCidade(idCidade, 22, 1454));
                distancias.add(setDistanciaCidade(idCidade, 23, 1386));
                distancias.add(setDistanciaCidade(idCidade, 24, 1776));
                distancias.add(setDistanciaCidade(idCidade, 25, 1401));
                distancias.add(setDistanciaCidade(idCidade, 26, 1401));
                break;
            case 17:
                distancias.add(setDistanciaCidade(idCidade, 1, 3296));
                distancias.add(setDistanciaCidade(idCidade, 2, 3852));
                distancias.add(setDistanciaCidade(idCidade, 3, 1712));
                distancias.add(setDistanciaCidade(idCidade, 4, 5348));
                distancias.add(setDistanciaCidade(idCidade, 5, 2027));
                distancias.add(setDistanciaCidade(idCidade, 6, 1518));
                distancias.add(setDistanciaCidade(idCidade, 7, 2206));
                distancias.add(setDistanciaCidade(idCidade, 8, 711));
                distancias.add(setDistanciaCidade(idCidade, 9, 476));
                distancias.add(setDistanciaCidade(idCidade, 10, 4242));
                distancias.add(setDistanciaCidade(idCidade, 11, 1847));
                distancias.add(setDistanciaCidade(idCidade, 12, 3889));
                distancias.add(setDistanciaCidade(idCidade, 13, 3572));
                distancias.add(setDistanciaCidade(idCidade, 14, 4563));
                distancias.add(setDistanciaCidade(idCidade, 15, 4066));
                distancias.add(setDistanciaCidade(idCidade, 16, 2747));
                distancias.add(setDistanciaCidade(idCidade, 18, 3662));
                distancias.add(setDistanciaCidade(idCidade, 19, 3779));
                distancias.add(setDistanciaCidade(idCidade, 20, 4196));
                distancias.add(setDistanciaCidade(idCidade, 21, 1553));
                distancias.add(setDistanciaCidade(idCidade, 22, 3090));
                distancias.add(setDistanciaCidade(idCidade, 23, 3891));
                distancias.add(setDistanciaCidade(idCidade, 24, 1109));
                distancias.add(setDistanciaCidade(idCidade, 25, 3804));
                distancias.add(setDistanciaCidade(idCidade, 26, 2001));
                break;
            case 18:
                distancias.add(setDistanciaCidade(idCidade, 1, 4230));
                distancias.add(setDistanciaCidade(idCidade, 2, 4397));
                distancias.add(setDistanciaCidade(idCidade, 3, 3050));
                distancias.add(setDistanciaCidade(idCidade, 4, 1686));
                distancias.add(setDistanciaCidade(idCidade, 5, 2589));
                distancias.add(setDistanciaCidade(idCidade, 6, 2150));
                distancias.add(setDistanciaCidade(idCidade, 7, 1456));
                distancias.add(setDistanciaCidade(idCidade, 8, 3135));
                distancias.add(setDistanciaCidade(idCidade, 9, 3442));
                distancias.add(setDistanciaCidade(idCidade, 10, 4862));
                distancias.add(setDistanciaCidade(idCidade, 11, 2390));
                distancias.add(setDistanciaCidade(idCidade, 12, 4822));
                distancias.add(setDistanciaCidade(idCidade, 13, 4505));
                distancias.add(setDistanciaCidade(idCidade, 14, 901));
                distancias.add(setDistanciaCidade(idCidade, 15, 4998));
                distancias.add(setDistanciaCidade(idCidade, 16, 2970));
                distancias.add(setDistanciaCidade(idCidade, 17, 3662));
                distancias.add(setDistanciaCidade(idCidade, 19, 4712));
                distancias.add(setDistanciaCidade(idCidade, 20, 544));
                distancias.add(setDistanciaCidade(idCidade, 21, 3473));
                distancias.add(setDistanciaCidade(idCidade, 22, 4023));
                distancias.add(setDistanciaCidade(idCidade, 23, 4434));
                distancias.add(setDistanciaCidade(idCidade, 24, 3070));
                distancias.add(setDistanciaCidade(idCidade, 25, 4366));
                distancias.add(setDistanciaCidade(idCidade, 26, 3575));
                break;
            case 19:
                distancias.add(setDistanciaCidade(idCidade, 1, 501));
                distancias.add(setDistanciaCidade(idCidade, 2, 2074));
                distancias.add(setDistanciaCidade(idCidade, 3, 2061));
                distancias.add(setDistanciaCidade(idCidade, 4, 6483));
                distancias.add(setDistanciaCidade(idCidade, 5, 2135));
                distancias.add(setDistanciaCidade(idCidade, 6, 3247));
                distancias.add(setDistanciaCidade(idCidade, 7, 3255));
                distancias.add(setDistanciaCidade(idCidade, 8, 3078));
                distancias.add(setDistanciaCidade(idCidade, 9, 3375));
                distancias.add(setDistanciaCidade(idCidade, 10, 800));
                distancias.add(setDistanciaCidade(idCidade, 11, 2332));
                distancias.add(setDistanciaCidade(idCidade, 12, 120));
                distancias.add(setDistanciaCidade(idCidade, 13, 285));
                distancias.add(setDistanciaCidade(idCidade, 14, 5698));
                distancias.add(setDistanciaCidade(idCidade, 15, 297));
                distancias.add(setDistanciaCidade(idCidade, 16, 2058));
                distancias.add(setDistanciaCidade(idCidade, 17, 3779));
                distancias.add(setDistanciaCidade(idCidade, 18, 4712));
                distancias.add(setDistanciaCidade(idCidade, 20, 5243));
                distancias.add(setDistanciaCidade(idCidade, 21, 2338));
                distancias.add(setDistanciaCidade(idCidade, 22, 839));
                distancias.add(setDistanciaCidade(idCidade, 23, 1573));
                distancias.add(setDistanciaCidade(idCidade, 24, 2660));
                distancias.add(setDistanciaCidade(idCidade, 25, 1137));
                distancias.add(setDistanciaCidade(idCidade, 26, 1831));
                break;
            case 20:
                distancias.add(setDistanciaCidade(idCidade, 1, 4763));
                distancias.add(setDistanciaCidade(idCidade, 2, 4931));
                distancias.add(setDistanciaCidade(idCidade, 3, 3584));
                distancias.add(setDistanciaCidade(idCidade, 4, 2230));
                distancias.add(setDistanciaCidade(idCidade, 5, 3123));
                distancias.add(setDistanciaCidade(idCidade, 6, 2684));
                distancias.add(setDistanciaCidade(idCidade, 7, 1990));
                distancias.add(setDistanciaCidade(idCidade, 8, 3669));
                distancias.add(setDistanciaCidade(idCidade, 9, 3976));
                distancias.add(setDistanciaCidade(idCidade, 10, 5396));
                distancias.add(setDistanciaCidade(idCidade, 11, 2924));
                distancias.add(setDistanciaCidade(idCidade, 12, 5356));
                distancias.add(setDistanciaCidade(idCidade, 13, 5039));
                distancias.add(setDistanciaCidade(idCidade, 14, 1445));
                distancias.add(setDistanciaCidade(idCidade, 15, 5533));
                distancias.add(setDistanciaCidade(idCidade, 16, 3764));
                distancias.add(setDistanciaCidade(idCidade, 17, 4196));
                distancias.add(setDistanciaCidade(idCidade, 18, 544));
                distancias.add(setDistanciaCidade(idCidade, 19, 5243));
                distancias.add(setDistanciaCidade(idCidade, 21, 4007));
                distancias.add(setDistanciaCidade(idCidade, 22, 4457));
                distancias.add(setDistanciaCidade(idCidade, 23, 4968));
                distancias.add(setDistanciaCidade(idCidade, 24, 3604));
                distancias.add(setDistanciaCidade(idCidade, 25, 4900));
                distancias.add(setDistanciaCidade(idCidade, 26, 4109));
                break;
            case 21:
                distancias.add(setDistanciaCidade(idCidade, 1, 1855));
                distancias.add(setDistanciaCidade(idCidade, 2, 3250));
                distancias.add(setDistanciaCidade(idCidade, 3, 434));
                distancias.add(setDistanciaCidade(idCidade, 4, 5159));
                distancias.add(setDistanciaCidade(idCidade, 5, 1148));
                distancias.add(setDistanciaCidade(idCidade, 6, 1444));
                distancias.add(setDistanciaCidade(idCidade, 7, 2017));
                distancias.add(setDistanciaCidade(idCidade, 8, 852));
                distancias.add(setDistanciaCidade(idCidade, 9, 1144));
                distancias.add(setDistanciaCidade(idCidade, 10, 2805));
                distancias.add(setDistanciaCidade(idCidade, 11, 1338));
                distancias.add(setDistanciaCidade(idCidade, 12, 2448));
                distancias.add(setDistanciaCidade(idCidade, 13, 2131));
                distancias.add(setDistanciaCidade(idCidade, 14, 4374));
                distancias.add(setDistanciaCidade(idCidade, 15, 2625));
                distancias.add(setDistanciaCidade(idCidade, 16, 2124));
                distancias.add(setDistanciaCidade(idCidade, 17, 1553));
                distancias.add(setDistanciaCidade(idCidade, 18, 3473));
                distancias.add(setDistanciaCidade(idCidade, 19, 2338));
                distancias.add(setDistanciaCidade(idCidade, 20, 4007));
                distancias.add(setDistanciaCidade(idCidade, 22, 1649));
                distancias.add(setDistanciaCidade(idCidade, 23, 3015));
                distancias.add(setDistanciaCidade(idCidade, 24, 429));
                distancias.add(setDistanciaCidade(idCidade, 25, 2579));
                distancias.add(setDistanciaCidade(idCidade, 26, 521));
                break;
            case 22:
                distancias.add(setDistanciaCidade(idCidade, 1, 356));
                distancias.add(setDistanciaCidade(idCidade, 2, 2100));
                distancias.add(setDistanciaCidade(idCidade, 3, 1372));
                distancias.add(setDistanciaCidade(idCidade, 4, 5794));
                distancias.add(setDistanciaCidade(idCidade, 5, 1446));
                distancias.add(setDistanciaCidade(idCidade, 6, 2568));
                distancias.add(setDistanciaCidade(idCidade, 7, 2566));
                distancias.add(setDistanciaCidade(idCidade, 8, 2385));
                distancias.add(setDistanciaCidade(idCidade, 9, 2682));
                distancias.add(setDistanciaCidade(idCidade, 10, 1389));
                distancias.add(setDistanciaCidade(idCidade, 11, 1643));
                distancias.add(setDistanciaCidade(idCidade, 12, 949));
                distancias.add(setDistanciaCidade(idCidade, 13, 632));
                distancias.add(setDistanciaCidade(idCidade, 14, 5009));
                distancias.add(setDistanciaCidade(idCidade, 15, 1126));
                distancias.add(setDistanciaCidade(idCidade, 16, 1454));
                distancias.add(setDistanciaCidade(idCidade, 17, 3090));
                distancias.add(setDistanciaCidade(idCidade, 18, 4023));
                distancias.add(setDistanciaCidade(idCidade, 19, 839));
                distancias.add(setDistanciaCidade(idCidade, 20, 4457));
                distancias.add(setDistanciaCidade(idCidade, 21, 1649));
                distancias.add(setDistanciaCidade(idCidade, 23, 1599));
                distancias.add(setDistanciaCidade(idCidade, 24, 1962));
                distancias.add(setDistanciaCidade(idCidade, 25, 1163));
                distancias.add(setDistanciaCidade(idCidade, 26, 1202));
                break;
            case 23:
                distancias.add(setDistanciaCidade(idCidade, 1, 1578));
                distancias.add(setDistanciaCidade(idCidade, 2, 806));
                distancias.add(setDistanciaCidade(idCidade, 3, 2738));
                distancias.add(setDistanciaCidade(idCidade, 4, 6120));
                distancias.add(setDistanciaCidade(idCidade, 5, 2157));
                distancias.add(setDistanciaCidade(idCidade, 6, 2979));
                distancias.add(setDistanciaCidade(idCidade, 7, 2978));
                distancias.add(setDistanciaCidade(idCidade, 8, 3230));
                distancias.add(setDistanciaCidade(idCidade, 9, 3537));
                distancias.add(setDistanciaCidade(idCidade, 10, 1070));
                distancias.add(setDistanciaCidade(idCidade, 11, 2054));
                distancias.add(setDistanciaCidade(idCidade, 12, 1660));
                distancias.add(setDistanciaCidade(idCidade, 13, 1672));
                distancias.add(setDistanciaCidade(idCidade, 14, 5335));
                distancias.add(setDistanciaCidade(idCidade, 15, 1607));
                distancias.add(setDistanciaCidade(idCidade, 16, 1386));
                distancias.add(setDistanciaCidade(idCidade, 17, 3891));
                distancias.add(setDistanciaCidade(idCidade, 18, 4434));
                distancias.add(setDistanciaCidade(idCidade, 19, 1573));
                distancias.add(setDistanciaCidade(idCidade, 20, 4968));
                distancias.add(setDistanciaCidade(idCidade, 21, 3015));
                distancias.add(setDistanciaCidade(idCidade, 22, 1599));
                distancias.add(setDistanciaCidade(idCidade, 24, 2970));
                distancias.add(setDistanciaCidade(idCidade, 25, 446));
                distancias.add(setDistanciaCidade(idCidade, 26, 2607));
                break;
            case 24:
                distancias.add(setDistanciaCidade(idCidade, 1, 2187));
                distancias.add(setDistanciaCidade(idCidade, 2, 2933));
                distancias.add(setDistanciaCidade(idCidade, 3, 586));
                distancias.add(setDistanciaCidade(idCidade, 4, 4756));
                distancias.add(setDistanciaCidade(idCidade, 5, 1015));
                distancias.add(setDistanciaCidade(idCidade, 6, 1014));
                distancias.add(setDistanciaCidade(idCidade, 7, 1614));
                distancias.add(setDistanciaCidade(idCidade, 8, 408));
                distancias.add(setDistanciaCidade(idCidade, 9, 705));
                distancias.add(setDistanciaCidade(idCidade, 10, 3127));
                distancias.add(setDistanciaCidade(idCidade, 11, 926));
                distancias.add(setDistanciaCidade(idCidade, 12, 2770));
                distancias.add(setDistanciaCidade(idCidade, 13, 2453));
                distancias.add(setDistanciaCidade(idCidade, 14, 3971));
                distancias.add(setDistanciaCidade(idCidade, 15, 2947));
                distancias.add(setDistanciaCidade(idCidade, 16, 1776));
                distancias.add(setDistanciaCidade(idCidade, 17, 1109));
                distancias.add(setDistanciaCidade(idCidade, 18, 3070));
                distancias.add(setDistanciaCidade(idCidade, 19, 2660));
                distancias.add(setDistanciaCidade(idCidade, 20, 3604));
                distancias.add(setDistanciaCidade(idCidade, 21, 429));
                distancias.add(setDistanciaCidade(idCidade, 22, 1962));
                distancias.add(setDistanciaCidade(idCidade, 23, 2970));
                distancias.add(setDistanciaCidade(idCidade, 25, 2792));
                distancias.add(setDistanciaCidade(idCidade, 26, 882));
                break;
            case 25:
                distancias.add(setDistanciaCidade(idCidade, 1, 1142));
                distancias.add(setDistanciaCidade(idCidade, 2, 947));
                distancias.add(setDistanciaCidade(idCidade, 3, 2302));
                distancias.add(setDistanciaCidade(idCidade, 4, 6052));
                distancias.add(setDistanciaCidade(idCidade, 5, 1789));
                distancias.add(setDistanciaCidade(idCidade, 6, 2911));
                distancias.add(setDistanciaCidade(idCidade, 7, 2910));
                distancias.add(setDistanciaCidade(idCidade, 8, 3143));
                distancias.add(setDistanciaCidade(idCidade, 9, 3450));
                distancias.add(setDistanciaCidade(idCidade, 10, 634));
                distancias.add(setDistanciaCidade(idCidade, 11, 1986));
                distancias.add(setDistanciaCidade(idCidade, 12, 1224));
                distancias.add(setDistanciaCidade(idCidade, 13, 1236));
                distancias.add(setDistanciaCidade(idCidade, 14, 5267));
                distancias.add(setDistanciaCidade(idCidade, 15, 1171));
                distancias.add(setDistanciaCidade(idCidade, 16, 1401));
                distancias.add(setDistanciaCidade(idCidade, 17, 3804));
                distancias.add(setDistanciaCidade(idCidade, 18, 4366));
                distancias.add(setDistanciaCidade(idCidade, 19, 1137));
                distancias.add(setDistanciaCidade(idCidade, 20, 4900));
                distancias.add(setDistanciaCidade(idCidade, 21, 2579));
                distancias.add(setDistanciaCidade(idCidade, 22, 1163));
                distancias.add(setDistanciaCidade(idCidade, 23, 446));
                distancias.add(setDistanciaCidade(idCidade, 24, 2792));
                distancias.add(setDistanciaCidade(idCidade, 26, 2171));
                break;
            case 26:
                distancias.add(setDistanciaCidade(idCidade, 1, 1408));
                distancias.add(setDistanciaCidade(idCidade, 2, 3108));
                distancias.add(setDistanciaCidade(idCidade, 3, 524));
                distancias.add(setDistanciaCidade(idCidade, 4, 5261));
                distancias.add(setDistanciaCidade(idCidade, 5, 1239));
                distancias.add(setDistanciaCidade(idCidade, 6, 1892));
                distancias.add(setDistanciaCidade(idCidade, 7, 2119));
                distancias.add(setDistanciaCidade(idCidade, 8, 1300));
                distancias.add(setDistanciaCidade(idCidade, 9, 1597));
                distancias.add(setDistanciaCidade(idCidade, 10, 2397));
                distancias.add(setDistanciaCidade(idCidade, 11, 1428));
                distancias.add(setDistanciaCidade(idCidade, 12, 2001));
                distancias.add(setDistanciaCidade(idCidade, 13, 1684));
                distancias.add(setDistanciaCidade(idCidade, 14, 4476));
                distancias.add(setDistanciaCidade(idCidade, 15, 2178));
                distancias.add(setDistanciaCidade(idCidade, 16, 2214));
                distancias.add(setDistanciaCidade(idCidade, 17, 2001));
                distancias.add(setDistanciaCidade(idCidade, 18, 3575));
                distancias.add(setDistanciaCidade(idCidade, 19, 1831));
                distancias.add(setDistanciaCidade(idCidade, 20, 4109));
                distancias.add(setDistanciaCidade(idCidade, 21, 521));
                distancias.add(setDistanciaCidade(idCidade, 22, 1202));
                distancias.add(setDistanciaCidade(idCidade, 23, 2607));
                distancias.add(setDistanciaCidade(idCidade, 24, 882));
                distancias.add(setDistanciaCidade(idCidade, 25, 2171));
                break;
        }
        
        return distancias;
    }
    
    public static DistanciaCidades setDistanciaCidade(int idCidade, int idCidadeDestino, int distancia) {
        DistanciaCidades distanciaCidades = new DistanciaCidades();
        distanciaCidades.idCidadeOrigem = idCidade;
        distanciaCidades.idCidadeDestino = idCidadeDestino;
        distanciaCidades.distancia = distancia;
        
        return distanciaCidades;
    }
}
